### ISSUE TITLE
Error reading device control characteristics

### ISSUE THREAD

**Issue by Norton-breman** [adamkewley/xdc#1]
Hi,
I'm trying to get dot working in record mode not in streaming one. And I need to know (and later modify) each device tag. Using your code I ound that you do not read all the tag bytes which lead to wrong values for the next informations (i.e output_rate, filter_profil and reserved ).
To fix it you need to read all the 16 bytes of the tag and just decode the ones corresponding to tag_len as follow (line 115) :
`rv.device_tag = r.raw(16)[:rv.device_tag_len].decode("ascii")`

Cheers
Antoine

**Comment by adamkewley** [comment]
Ooh, nice spot @Norton-breman - I'll make the change and test it against the DOT I have hanging around

Sorry that the code is a bit buggy. It was kind of hacked together to see if we could have pure python bindings to a DOT that we have in the lab. Previously, a student was combining several languages/applications together to use the DOT. The setup made my eyes water enough to merit writing an implementation from scratch (this). However, I only budgeted a day or two to do this, so I focused on getting the bare-minimum functionality then stopped, so most of the DOT's BLE spec isn't implemented :(

Either way, I hope the codebase is readable enough to be useful for you!

**Comment by Norton-breman** [comment]
Don't be sorry :-) ! I'm in the same condition, I need to be able to start a record without using the xsens app because of the numerous languages requiered. This in order to integrate dots in my lab's workfow. So your code is a good place to start !
If you want, i will let you know if I can achieve my goal, but i'm afraid I'm not knowing asyncio enough to make something clean.

**Comment by adamkewley** [comment]
This has been fixed in the latest round of DOT hacking I'm doing over xmas
