### ISSUE TITLE
AttributeError: module 'xdc' has no attribute 'DotDevice'

### ISSUE THREAD

**Issue by Allwillcome** [adamkewley/xdc#2]
hello， adamkewley
I am also using Xsens Dot. I tried to script Xsens Dot using the official way of Xsens Dot but failed. Then I happened to see your work，What a lifesaver.
But when I used your code, a little error occurred:
```powershell
  File "<stdin>", line 1, in <module>
  File "E:\program\Anaconda3\envs\xsensdotConnector\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "<stdin>", line 4, in run
  AttributeError: module 'xdc' has no attribute 'DotDevice'
```

I used Anaconda to create a new virtual environment with version 3.9.1 and successfully installed dependencies
My computer system is Windows, and when I run the code, it turns on Bluetooth and Xsens Dot
I was able to execute the following code successfully
```powershell
>>> import xdc
>>> import asyncio
>>> async def run():
...     dot_bles = await xdc.scan_for_DOT_BLEDevices()
...     for dot_ble in dot_bles:
...         async with xdc.DotDevice(dot_ble) as dot:
...             info = await d.device_info()
...             print(info)
... 
>>> loop = asyncio.get_event_loop()
```
If you have time, I hope you can get your help, and maybe we can work together to make XDC code more robust and help more people

Thank You

**Comment by adamkewley** [comment]
@Allwillcome ah, sorry about this, I think the issue here is that the code example in the README uses `DotDevice`:

```python
# WRONG
import xdc
import asyncio

async def run():
    dot_bles = await xdc.scan_for_DOT_BLEDevices()
    for dot_ble in dot_bles:
        async with xdc.DotDevice(dot_ble) as dot:
            info = await d.device_info()
            print(info)
            
loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

But the implementation file renames it to `Dot` ([here](https://github.com/adamkewley/xdc/blob/master/xdc.py#L336)):

```python

async def async_run():
    dots = await scan_for_DOT_BLEDevices()
    for dot in dots:
        async with Dot(dot) as d:
            await d.enable_measurement_action()
            h = ResponseHandler()
            await d.start_notify_medium_payload(h)
            await asyncio.sleep(5.0)

def run():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(async_run())
```

So, in principle, running `xdc.run()` *should* work - I'll look into updating the README accordingly.

**Comment by Allwillcome** [comment]
Thank you for your reply. I have successfully collected 290 numbers of the four sensors. After collecting 290 numbers, the program stopped automatically again
```powershell
i=289 t=672898335 x=(0.5923872590065002,), y=(0.3496272563934326,), z=(-0.5528647899627686,)
Traceback (most recent call last):
  File "E:\program\Anaconda3\envs\xsensdotConnector\lib\asyncio\locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\program\Anaconda3\envs\xsensdotConnector\lib\asyncio\tasks.py", line 489, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Workspace\xdc\xdc.py", line 347, in run
    loop.run_until_complete(async_run())
  File "E:\program\Anaconda3\envs\xsensdotConnector\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\Workspace\xdc\xdc.py", line 343, in async_run
    await asyncio.sleep(5.0)
  File "E:\Workspace\xdc\xdc.py", line 299, in __aexit__
    await self.client.__aexit__(exc_type, value, traceback)
  File "E:\program\Anaconda3\envs\xsensdotConnector\lib\site-packages\bleak\backends\client.py", line 65, in __aexit__
    await self.disconnect()
  File "E:\program\Anaconda3\envs\xsensdotConnector\lib\site-packages\bleak\backends\winrt\client.py", line 262, in disconnect
    await asyncio.wait_for(event.wait(), timeout=10)
  File "E:\program\Anaconda3\envs\xsensdotConnector\lib\asyncio\tasks.py", line 491, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by Kris5GJ** [comment]
Hello Adam, thank you for making this available.
I'm a basic python user.
I have a set of XSens Dot but I don't have a cellphone to connect them, so I'm trying to register in my computer.
I installed everything as stated in the README.
I ran into an error trying to run the following:
import xdc
import asyncio

async def run():
    dot_bles = await xdc.scan_for_DOT_BLEDevices()
    for dot_ble in dot_bles:
        async with xdc.DotDevice(dot_ble) as dot:
            info = await d.device_info()
            print(info)
            
loop = asyncio.get_event_loop()
loop.run_until_complete(run())

Then I came here and saw this:
async def async_run():
    dots = await scan_for_DOT_BLEDevices()
    for dot in dots:
        async with Dot(dot) as d:
            await d.enable_measurement_action()
            h = ResponseHandler()
            await d.start_notify_medium_payload(h)
            await asyncio.sleep(5.0)

def run():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(async_run())

I ran it, and got no error. But now I don't know what to do to verify connection or start registering.

I appreciate if any of you could give me a hint.

Thank you in advance.

**Comment by adamkewley** [comment]
Hi @Kris5GJ 

This codebase is extremely experimental, so it's no surprise that you are running into problems.

I have updated the README with more example code and added a Q&A section to clarify the design etc., but I don't have much time to develop the codebase robustly - this isn't my main project, at all.

I can't help much with your specific example because you have no error. I'm assuming that the reason you have no error is because you didn't run any actual code? Your example code only contains function definitions, which won't automatically run until you call them, e.g. with:

```python
run()
```

If there is a specific issue that you'd like me to look into then please open a separate issue ticket, just so that I can clearly see there's something new hanging around. I saw this one only because I'm tagged in it and received an automatic email from GitHub :<
