### ISSUE TITLE
Geting error while running the example code on wsl

### ISSUE THREAD

**Issue by hacihasansavan** [adamkewley/xdc#3]
Hi Adam,
Thank you for your effort.
I'm trying to run this on wsl but getting this error:

![image](https://user-images.githubusercontent.com/57284868/195837330-3ac765df-33b0-457b-934c-b3f5a9cd5f70.png)
![image](https://user-images.githubusercontent.com/57284868/195837688-bd7a369a-059b-40fb-b338-2b19b6129c29.png)

**Example_Usage.py** is the code that you gave in readme
I would be very appreciated if you can help. Thank you

**Comment by adamkewley** [comment]
It looks like `bleak` (the python library) is trying to use `bluetoothctl` (the Linux application for handling bluetooth connections) to set up your bluetooth connection.

It might be that you can look up "install `bluetoothctl`" or similar - that's the application that you need to have installed in order for `bleak` to actually be able to connect to the bluetooth device.

Beware, though, this depends heavily on what WSL forwards to the underlying Windows operating system. It might be that WSL does not support forwarding bluetooth connections to the WSL container/VM/however-they-do-it

**Comment by hacihasansavan** [comment]
thanks, I just solved it by using windows PowerShell. Probably it was related with what you said about wsl in your last sentence.
