### ISSUE TITLE
Waits to take data but no data coming from xsens

### ISSUE THREAD

**Issue by hacihasansavan** [adamkewley/xdc#4]
Hi adam, thanks alot for your code,

I run the example code that you gave and reaches the and with no error but I'm not be able to get data from xsens device that connected.
it waits but no data coming or maybe I'm doing something wrong

![image](https://user-images.githubusercontent.com/57284868/196898401-c6db7b19-346b-4da4-90cd-ee60877ff3d6.png)
![image](https://user-images.githubusercontent.com/57284868/196898472-ff62dc2c-a3e0-490a-b527-d9940cd36198.png)

**Comment by hacihasansavan** [comment]
An also I'm getting that output. I couldn't understand that is error or some just an information message. (Maybe It is related with above)

![image](https://user-images.githubusercontent.com/57284868/196905399-1df81aff-2dea-4bcc-a953-58608a00cd34.png)

![image](https://user-images.githubusercontent.com/57284868/196904830-e8180d31-d44e-4117-9d83-c49e65e5b913.png)

**Comment by hacihasansavan** [comment]
when i press button once, it detects and gives that exception:
(still doesn't read movements data that coming from the xsens device)

![image](https://user-images.githubusercontent.com/57284868/196939367-ac53c896-57cd-433e-be11-5cc5ff3d6196.png)

![image](https://user-images.githubusercontent.com/57284868/196939889-ce04dbc4-97c6-4ac9-a66a-38e597979427.png)

**Comment by adamkewley** [comment]
> when i press button once, it detects and gives that exception: (still doesn't read movements data that coming from the xsens device)

That is a bug in the code. It should be `end`, rather than `reader.end`. Or the entire expression can be `rv.unused = reader.read_bytes(reader.remaining())`

**Comment by adamkewley** [comment]
> Hi adam, thanks alot for your code,
> 
> I run the example code that you gave and reaches the and with no error but I'm not be able to get data from xsens device that connected. it waits but no data coming or maybe I'm doing something wrong


Did your code here enable sending notifications? You have subscribed to notifications but you first need to play around with the `Device Control Characteristic` API to tell the XSens which data to emit and at what rate. IIRC, the DOT defaults to emitting no data initially.

**Comment by adamkewley** [comment]
> An also I'm getting that output. I couldn't understand that is error or some just an information message. (Maybe It is related with above)

This looks like an error in the DOT/driver, where it has a crap device ID. It could happen if (e.g.) XSens hasn't paid whichever consortium reserves device IDs. Unlikely to be an error if other parts of the API work (e.g. blinking a light etc.)

**Comment by adamkewley** [comment]
As  I mention in the README, this isn't an actively maintained project and is just some experimental code that I threw online when I was playing with a DOT during a christmas break.

I would strongly recommend reading through the XSens BLE spec (the PDF in the repo), and maybe reading this source code in more detail, before trying to build something functional - this demo code will maybe get you 80 % of the way there but I currently have other active projects and have no time to maintain this.

**Comment by formidify** [comment]
@hacihasansavan Hi! I think I am currently facing the same issue of not being able to get any output. Wondering if you have managed to make it work. Any help is much appreciated!

**Comment by hacihasansavan** [comment]
Hi, I didn't continue the project, for that reason ı didn't do any fix about this code. If you use linux I recommend you use this repo: https://github.com/aero-man/xsens-dot-python  this works well on linux. also, i heard that xsens released something for streaming realtime data, may be you can ask them.
